name: moneyApp
description: .

publish_to: 'none'

version: 3.3.2+33

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:  
  animations: ^2.0.7
  chart_sparkline: ^1.0.12 
  csv: ^5.0.1
  dart_code_metrics: ^5.3.0
  date_picker_timeline: ^1.2.3 
  device_info_plus:  
  dynamic_color: ^1.5.4
  equatable: ^2.0.5
  file_picker: ^5.2.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1 
  flutter_localizations:
    sdk: flutter 
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  go_router: ^6.0.1
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  intl: ^0.17.0 
  local_auth: ^2.1.3
  material_color_utilities: ^0.2.0
  material_design_icons_flutter: ^6.0.7096
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  responsive_builder: ^0.5.0+1
  share_plus: ^6.3.0 
  url_launcher: ^6.1.7 
  url_strategy: ^0.2.0
  google_sign_in: ^5.1.1
  firebase_messaging: ^14.3.0
dev_dependencies:
  build_runner: ^2.3.2
  change_app_package_name: any
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.0+1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  
dependency_overrides:
  intl: ^0.18.0
  material_color_utilities: ^0.2.0 

flutter_app_name:
  name: "MoneyApp_taiducvng"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  color_dark: "#121212"
  android: true
  ios: true
  android_12:
    image: assets/images/imagesicon.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/imagesicon.png
    icon_background_color_dark: "#121212"

flutter_icons:
  image_path: "assets/images/imagesicon.png"
  ios: false
  android: true
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
